workspace 'AKForm.xcworkspace'
xcodeproj 'AKForm/AKForm.xcodeproj'

platform :ios, '7.0'

pod 'HexColors'
pod 'UIImage-Resize'
pod 'NSDate+Helper'
pod 'URBMediaFocusViewController@arkuana'
pod 'GKImagePicker@arkuana'
pod 'MHPrettyDate'

pod 'DAKeyboardControl', :git => 'https://github.com/isyiwang/DAKeyboardControl.git'
pod 'CJStringValidator', :git => "https://github.com/arkuana/CJStringValidator.git"
