workspace 'AKForm.xcworkspace'
xcodeproj 'AKForm/AKForm.xcodeproj'

platform :ios, '7.0'

pod 'HexColors'
pod 'UIImage-Resize'
pod 'NSDate+Helper'
pod 'CJStringValidator'
pod 'URBMediaFocusViewController@arkuana'

pod 'GKImagePicker@arkuana', :git => "https://github.com/arkuana/GKImagePicker.git"
